// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<MultichainAddresses> getMultichainAddresses({
  required String mnemonic,
}) => RustLib.instance.api.crateApiChainsGetMultichainAddresses(
  mnemonic: mnemonic,
);

/// Sign an EIP-1559 native transfer. Returns 0x-prefixed raw tx hex for
/// `eth_sendRawTransaction`. Amounts are decimal wei strings.
Future<String> signEthTransaction({
  required String mnemonic,
  required BigInt chainId,
  required BigInt nonce,
  required String maxPriorityFeePerGasWei,
  required String maxFeePerGasWei,
  required BigInt gasLimit,
  required String to,
  required String valueWei,
}) => RustLib.instance.api.crateApiChainsSignEthTransaction(
  mnemonic: mnemonic,
  chainId: chainId,
  nonce: nonce,
  maxPriorityFeePerGasWei: maxPriorityFeePerGasWei,
  maxFeePerGasWei: maxFeePerGasWei,
  gasLimit: gasLimit,
  to: to,
  valueWei: valueWei,
);

/// Sign a P2WPKH transaction spending the given UTXOs. The implicit fee is
/// `sum(utxos) - amount - change` and must be positive. Returns raw tx hex
/// for Esplora `POST /tx`.
Future<String> signBtcTransaction({
  required String mnemonic,
  required List<ApiBtcUtxo> utxos,
  required String toAddress,
  required BigInt amountSats,
  required BigInt changeSats,
}) => RustLib.instance.api.crateApiChainsSignBtcTransaction(
  mnemonic: mnemonic,
  utxos: utxos,
  toAddress: toAddress,
  amountSats: amountSats,
  changeSats: changeSats,
);

/// Sign a Cosmos SDK bank MsgSend (SIGN_MODE_DIRECT). Returns base64(TxRaw)
/// for `POST /cosmos/tx/v1beta1/txs`. The from-address is derived from the
/// mnemonic and `hrp`.
Future<String> signCosmosSend({
  required String mnemonic,
  required String chainId,
  required String hrp,
  required BigInt accountNumber,
  required BigInt sequence,
  required String toAddress,
  required String amount,
  required String denom,
  required String feeAmount,
  required String feeDenom,
  required BigInt gasLimit,
  required String memo,
}) => RustLib.instance.api.crateApiChainsSignCosmosSend(
  mnemonic: mnemonic,
  chainId: chainId,
  hrp: hrp,
  accountNumber: accountNumber,
  sequence: sequence,
  toAddress: toAddress,
  amount: amount,
  denom: denom,
  feeAmount: feeAmount,
  feeDenom: feeDenom,
  gasLimit: gasLimit,
  memo: memo,
);

/// Sign a Solana system-program transfer. Returns base64 tx for
/// `sendTransaction`.
Future<String> signSolTransfer({
  required String mnemonic,
  required String recentBlockhash,
  required String toAddress,
  required BigInt lamports,
}) => RustLib.instance.api.crateApiChainsSignSolTransfer(
  mnemonic: mnemonic,
  recentBlockhash: recentBlockhash,
  toAddress: toAddress,
  lamports: lamports,
);

class ApiBtcUtxo {
  final String txid;
  final int vout;
  final BigInt valueSats;

  const ApiBtcUtxo({
    required this.txid,
    required this.vout,
    required this.valueSats,
  });

  @override
  int get hashCode => txid.hashCode ^ vout.hashCode ^ valueSats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBtcUtxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          valueSats == other.valueSats;
}

/// Per-chain receive addresses derived from one account mnemonic.
class MultichainAddresses {
  final String btc;
  final String eth;
  final String cosmos;
  final String sol;

  const MultichainAddresses({
    required this.btc,
    required this.eth,
    required this.cosmos,
    required this.sol,
  });

  @override
  int get hashCode =>
      btc.hashCode ^ eth.hashCode ^ cosmos.hashCode ^ sol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MultichainAddresses &&
          runtimeType == other.runtimeType &&
          btc == other.btc &&
          eth == other.eth &&
          cosmos == other.cosmos &&
          sol == other.sol;
}
